### ISSUE TITLE
Include `src` in NPM release

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/web3-events#3]
In order to improve the Developer experience when using this library I think we should include the source code in NPM, so developers can look at the code. Currently it is not being included in `node_modules` when we this library is installed.

![image](https://user-images.githubusercontent.com/56316686/96872291-d42fc280-1449-11eb-9801-3fc31244a0b8.png)

**Comment by AuHau** [comment]
Sorry, but that is not the point of NPM packages. If you want to browse the original source code, you can go to its GitHub repo and check the non-compiled code. NPM package is a distribution package that should be as minimal as possible.
